/*
 Copyright (c) 2019 Mastercard
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import Foundation

public enum CountryCode: String {
    case af = "AF" /// Afghanistan
    case al = "AL" /// Albania
    case dz = "DZ" /// Algeria
    case `as` = "AS" /// American Samoa
    case ad = "AD" /// Andorra
    case ao = "AO" /// Angola
    case ai = "AI" /// Anguilla
    case aq = "AQ" /// Antarctica
    case ag = "AG" /// Antigua And Barbuda
    case ar = "AR" /// Argentina
    case am = "AM" /// Armenia
    case aw = "AW" /// Aruba
    case au = "AU" /// Australia
    case at = "AT" /// Austria
    case az = "AZ" /// Azerbaijan
    case bs = "BS" /// Bahamas
    case bh = "BH" /// Bahrain
    case bd = "BD" /// Bangladesh
    case bb = "BB" /// Barbados
    case by = "BY" /// Belarus
    case be = "BE" /// Belgium
    case bz = "BZ" /// Belize
    case bj = "BJ" /// Benin
    case bm = "BM" /// Bermuda
    case bt = "BT" /// Bhutan
    case bo = "BO" /// Bolivia
    case ba = "BA" /// Bosnia And Herzegovina
    case bw = "BW" /// Botswana
    case bv = "BV" /// Bouvet Island
    case br = "BR" /// Brazil
    case io = "IO" /// British Indian Ocean Territory
    case bn = "BN" /// Brunei Darussalam
    case bg = "BG" /// Bulgaria
    case bf = "BF" /// Burkina Faso
    case bi = "BI" /// Burundi
    case kh = "KH" /// Cambodia
    case cm = "CM" /// Cameroon
    case ca = "CA" /// Canada
    case cv = "CV" /// Cape Verde
    case ky = "KY" /// Cayman Islands
    case cf = "CF" /// Central African Republic
    case td = "TD" /// Chad
    case cl = "CL" /// Chile
    case cn = "CN" /// China
    case cx = "CX" /// Christmas Island
    case cc = "CC" /// Cocos (Keeling) Islands
    case co = "CO" /// Colombia
    case km = "KM" /// Comoros
    case cg = "CG" /// Congo
    case cd = "CD" /// Congo, The Democratic Republic Of The
    case ck = "CK" /// Cook Islands
    case cr = "CR" /// Costa Rica
    case ci = "CI" /// Cote D'Ivoire
    case hr = "HR" /// Croatia
    case cu = "CU" /// Cuba
    case cy = "CY" /// Cyprus
    case cz = "CZ" /// Czech Republic
    case dk = "DK" /// Denmark
    case dj = "DJ" /// Djibouti
    case dm = "DM" /// Dominica
    case `do` = "DO" /// Dominican Republic
    case tp = "TP" /// East Timor
    case ec = "EC" /// Ecuador
    case eg = "EG" /// Egypt
    case sv = "SV" /// El Salvador
    case gq = "GQ" /// Equatorial Guinea
    case er = "ER" /// Eritrea
    case ee = "EE" /// Estonia
    case et = "ET" /// Ethiopia
    case fk = "FK" /// Falkland Islands (Malvinas)
    case fo = "FO" /// Faroe Islands
    case fj = "FJ" /// Fiji
    case fi = "FI" /// Finland
    case fr = "FR" /// France
    case gf = "GF" /// French Guiana
    case pf = "PF" /// French Polynesia
    case tf = "TF" /// French Southern Territories
    case ga = "GA" /// Gabon
    case gm = "GM" /// Gambia
    case ge = "GE" /// Georgia
    case de = "DE" /// Germany
    case gh = "GH" /// Ghana
    case gi = "GI" /// Gibraltar
    case gr = "GR" /// Greece
    case gl = "GL" /// Greenland
    case gd = "GD" /// Grenada
    case gp = "GP" /// Guadeloupe
    case gu = "GU" /// Guam
    case gt = "GT" /// Guatemala
    case gn = "GN" /// Guinea
    case gw = "GW" /// Guinea-Bissau
    case gy = "GY" /// Guyana
    case ht = "HT" /// Haiti
    case hm = "HM" /// Heard Island And Mcdonald Islands
    case va = "VA" /// Holy See (Vatican City State)
    case hn = "HN" /// Honduras
    case hk = "HK" /// Hong Kong
    case hu = "HU" /// Hungary
    case `is` = "IS" /// Iceland
    case `in` = "IN" /// India
    case id = "ID" /// Indonesia
    case ir = "IR" /// Iran, Islamic Republic Of
    case iq = "IQ" /// Iraq
    case ie = "IE" /// Ireland
    case il = "IL" /// Israel
    case it = "IT" /// Italy
    case jm = "JM" /// Jamaica
    case jp = "JP" /// Japan
    case jo = "JO" /// Jordan
    case kz = "KZ" /// Kazakstan
    case ke = "KE" /// Kenya
    case ki = "KI" /// Kiribati
    case kp = "KP" /// Korea, Democratic People'S Republic Of
    case kr = "KR" /// Korea, Republic Of
    case kw = "KW" /// Kuwait
    case kg = "KG" /// Kyrgyzstan
    case la = "LA" /// Lao People'S Democratic Republic
    case lv = "LV" /// Latvia
    case lb = "LB" /// Lebanon
    case ls = "LS" /// Lesotho
    case lr = "LR" /// Liberia
    case ly = "LY" /// Libyan Arab Jamahiriya
    case li = "LI" /// Liechtenstein
    case lt = "LT" /// Lithuania
    case lu = "LU" /// Luxembourg
    case mo = "MO" /// Macau
    case mk = "MK" /// Macedonia, The Former Yugoslav Republic Of
    case mg = "MG" /// Madagascar
    case mw = "MW" /// Malawi
    case my = "MY" /// Malaysia
    case mv = "MV" /// Maldives
    case ml = "ML" /// Mali
    case mt = "MT" /// Malta
    case mh = "MH" /// Marshall Islands
    case mq = "MQ" /// Martinique
    case mr = "MR" /// Mauritania
    case mu = "MU" /// Mauritius
    case yt = "YT" /// Mayotte
    case mx = "MX" /// Mexico
    case fm = "FM" /// Micronesia, Federated States Of
    case md = "MD" /// Moldova, Republic Of
    case mc = "MC" /// Monaco
    case mn = "MN" /// Mongolia
    case ms = "MS" /// Montserrat
    case ma = "MA" /// Morocco
    case mz = "MZ" /// Mozambique
    case mm = "MM" /// Myanmar
    case na = "NA" /// Namibia
    case nr = "NR" /// Nauru
    case np = "NP" /// Nepal
    case nl = "NL" /// Netherlands
    case an = "AN" /// Netherlands Antilles
    case nc = "NC" /// New Caledonia
    case nz = "NZ" /// New Zealand
    case ni = "NI" /// Nicaragua
    case ne = "NE" /// Niger
    case ng = "NG" /// Nigeria
    case nu = "NU" /// Niue
    case nf = "NF" /// Norfolk Island
    case mp = "MP" /// Northern Mariana Islands
    case no = "NO" /// Norway
    case om = "OM" /// Oman
    case pk = "PK" /// Pakistan
    case pw = "PW" /// Palau
    case ps = "PS" /// Palestinian Territory, Occupied
    case pa = "PA" /// Panama
    case pg = "PG" /// Papua New Guinea
    case py = "PY" /// Paraguay
    case pe = "PE" /// Peru
    case ph = "PH" /// Philippines
    case pn = "PN" /// Pitcairn
    case pl = "PL" /// Poland
    case pt = "PT" /// Portugal
    case pr = "PR" /// Puerto Rico
    case qa = "QA" /// Qatar
    case re = "RE" /// Reunion
    case ro = "RO" /// Romania
    case ru = "RU" /// Russian Federation
    case rw = "RW" /// Rwanda
    case sh = "SH" /// Saint Helena
    case kn = "KN" /// Saint Kitts And Nevis
    case lc = "LC" /// Saint Lucia
    case pm = "PM" /// Saint Pierre And Miquelon
    case vc = "VC" /// Saint Vincent And The Grenadines
    case ws = "WS" /// Samoa
    case sm = "SM" /// San Marino
    case st = "ST" /// Sao Tome And Principe
    case sa = "SA" /// Saudi Arabia
    case sn = "SN" /// Senegal
    case sc = "SC" /// Seychelles
    case sl = "SL" /// Sierra Leone
    case sg = "SG" /// Singapore
    case sk = "SK" /// Slovakia
    case si = "SI" /// Slovenia
    case sb = "SB" /// Solomon Islands
    case so = "SO" /// Somalia
    case za = "ZA" /// South Africa
    case gs = "GS" /// South Georgia And The South Sandwich Islands
    case es = "ES" /// Spain
    case lk = "LK" /// Sri Lanka
    case sd = "SD" /// Sudan
    case sr = "SR" /// Suriname
    case sj = "SJ" /// Svalbard And Jan Mayen
    case sz = "SZ" /// Swaziland
    case se = "SE" /// Sweden
    case ch = "CH" /// Switzerland
    case sy = "SY" /// Syrian Arab Republic
    case tw = "TW" /// Taiwan, Province Of China
    case tj = "TJ" /// Tajikistan
    case tz = "TZ" /// Tanzania, United Republic Of
    case th = "TH" /// Thailand
    case tg = "TG" /// Togo
    case tk = "TK" /// Tokelau
    case to = "TO" /// Tonga
    case tt = "TT" /// Trinidad And Tobago
    case tn = "TN" /// Tunisia
    case tr = "TR" /// Turkey
    case tm = "TM" /// Turkmenistan
    case tc = "TC" /// Turks And Caicos Islands
    case tv = "TV" /// Tuvalu
    case ug = "UG" /// Uganda
    case ua = "UA" /// Ukraine
    case ae = "AE" /// United Arab Emirates
    case gb = "GB" /// United Kingdom
    case us = "US" /// United States
    case um = "UM" /// United States Minor Outlying Islands
    case uy = "UY" /// Uruguay
    case uz = "UZ" /// Uzbekistan
    case vu = "VU" /// Vanuatu
    case ve = "VE" /// Venezuela
    case vn = "VN" /// Viet Nam
    case vg = "VG" /// Virgin Islands, British
    case vi = "VI" /// Virgin Islands, U.S.
    case wf = "WF" /// Wallis And Futuna
    case eh = "EH" /// Western Sahara
    case ye = "YE" /// Yemen
    case yu = "YU" /// Yugoslavia
    case zm = "ZM" /// Zambia
    case zw = "ZW" /// Zimbabwe
}
